#!/bin/bash

source /home/bitergia/conf/requirements.cfg

# if RELEASE param is set, we download the info from
# https://github.com/Bitergia/mordred/tree/master/docker/unified_releases/
if [ $RELEASE ];
    then
    unset SORTINGHAT
    unset GRIMOIREELK
    unset MORDRED
    unset PANELS
    unset PERCEVAL
    unset PERCEVAL_MOZILLA
    unset REPORTS
    unset VIZGRIMOIREUTILS
    TMPFILE=`mktemp`
    wget https://raw.githubusercontent.com/Bitergia/mordred/master/docker/unified_releases/$RELEASE -O $TMPFILE
    source $TMPFILE
    rm $TMPFILE
    echo $RELEASE > /home/bitergia/release
else
    echo "customized release, see requirements.cfg file" > /home/bitergia/release
fi

# get SortingHat repository
cd /home/bitergia && \
git clone https://github.com/MetricsGrimoire/sortinghat.git && \
    cd sortinghat && \
    git checkout $SORTINGHAT && \
    sudo python3 setup.py install

# get GrimoireELK repository
cd /home/bitergia && \
git clone https://github.com/grimoirelab/GrimoireELK && \
    cd GrimoireELK && \
    git checkout $GRIMOIREELK

# get VizGrimoireUtils repository needed by mordred (eclipse projects)
cd /home/bitergia && \
git clone https://github.com/VizGrimoire/VizGrimoireUtils && \
    cd VizGrimoireUtils && \
    git checkout $VIZGRIMOIREUTILS

# get Mordred repository
cd /home/bitergia && \
git clone https://github.com/Bitergia/mordred.git mordred && \
    cd mordred && \
    git checkout $MORDRED

# panels for the dashboard
cd /home/bitergia && \
git clone https://github.com/grimoirelab/panels.git panels && \
    cd panels && \
    git checkout $PANELS

# reports repository
cd /home/bitergia && \
git clone https://github.com/grimoirelab/reports.git reports && \
    cd reports && \
    git checkout $REPORTS

# get Perceval repository
cd /home/bitergia && \
git clone https://github.com/grimoirelab/perceval.git && \
    cd perceval && \
    git checkout $PERCEVAL && \
    sudo python3 setup.py install

# perceval extras

# Mozilla ad-hoc backends

if [ $PERCEVAL_MOZILLA ]
    then
    cd /home/bitergia && \
        git clone https://github.com/grimoirelab/perceval-mozilla && \
        cd perceval-mozilla && \
        git checkout $PERCEVAL_MOZILLA && \
        sudo python3 setup.py install
fi

# some links we need until GrimoireELK and panels and reports can be installed
ln -s /home/bitergia/GrimoireELK/grimoire /home/bitergia/mordred/grimoire
ln -s /home/bitergia/GrimoireELK/grimoire_elk /home/bitergia/mordred/grimoire_elk
ln -s /home/bitergia/panels /home/bitergia/mordred/panels
ln -s /home/bitergia/reports /home/bitergia/mordred/reports

cd /home/bitergia/mordred && \
bin/mordred -c /home/bitergia/conf/setup.cfg
