#!/bin/bash

HOME_DIR='/home/grimoirelab'
CONF_DIR="$HOME_DIR/conf"

cd $HOMEDIR

source $CONF_DIR/requirements.cfg

if [ $RELEASE ]; then
    wget https://raw.githubusercontent.com/chaoss/grimoirelab/master/releases/$RELEASE -O $CONF_DIR/requirements.cfg
    echo $RELEASE > $HOME_DIR/release
else
    echo "customized release, see $CONF_DIR/requirements.cfg file" > $HOME_DIR/release
fi

# get grimoirelab repo for the build_grimoirelab script
git clone https://github.com/grimoirelab/grimoirelab.git --depth 1

echo "Installing and checking GrimoireLab Release"
sudo grimoirelab/utils/build_grimoirelab --build --install --check --install_system --relfile $CONF_DIR/requirements.cfg -l debug

# This could be an ENV var probably (it is defined in mordred conf)
REDIS="redis"

# arthur on
arthurd -g -d redis://$REDIS/8 --log-path $HOME_DIR/logs/arthurd --no-cache
# Give time to arthur to create the raw index
echo "Waiting for arthur startup completion ..."
sleep 5
echo "Starting two workers: collect and update tasks"
# Two workers
(arthurw -g -d redis://$REDIS/8 > $HOME_DIR/logs/worker-collect.log 2>&1) &
(arthurw -g -d redis://$REDIS/8 update > $HOME_DIR/logs/worker-update.log 2>&1) &

# Hack to get the panels menu file
wget https://raw.githubusercontent.com/grimoirelab/mordred/master/menu.yaml

mordred -c $HOME_DIR/conf/setup.cfg
